STATUS_TO_INTERNAL = {
    'CONFIRMED': 'CONFIRMED',
    'CANCELLED': 'CANCELLED',
    'READY_TO_PICKUP': 'READY',
    'READY_FOR_PICKUP': 'READY',
    'READY': 'READY',
    'DISPATCHED': 'DISPATCHED',
    'OUT_FOR_DELIVERY': 'DISPATCHED',
    'CONCLUDED': 'CONCLUDED',
    'DELIVERED': 'CONCLUDED',
}
INTERNAL_EVENT = {
    'CONFIRMED': ('CFM', 'CONFIRMED'),
    'CANCELLED': ('CAN', 'CANCELLED'),
    'READY': ('RTP', 'READY_TO_PICKUP'),
    'DISPATCHED': ('DSP', 'DISPATCHED'),
    'CONCLUDED': ('CON', 'CONCLUDED'),
}
